### ISSUE TITLE
Snapshot DateTime Serialization issue with Akka.NET 1.5.28

### ISSUE THREAD

**Issue by mooreja-zia** [akkadotnet/Akka.Persistence.Redis#362]
**Version Information**
Version of Akka.NET? 1.5.28
Which Akka.NET Modules? Akka.Persistence.Redis 1.5.24

**Describe the bug**
Calling SaveSnapshot on a ReceivePersistentActor results in the following exception:

```
Conversion from DateTime to Timestamp requires the DateTime kind to be Utc (Parameter 'dateTime')
System.ArgumentException: Conversion from DateTime to Timestamp requires the DateTime kind to be Utc (Parameter 'dateTime')
   at Google.Protobuf.WellKnownTypes.Timestamp.FromDateTime(DateTime dateTime)
   at Akka.Persistence.Redis.Serialization.PersistentSnapshotSerializer.ToBinary(Object obj)
   at Akka.Serialization.Serialization.WithTransport[T](ExtendedActorSystem system, Func`1 action)
   at Akka.Persistence.Redis.Snapshot.RedisSnapshotStore.SaveAsync(SnapshotMetadata metadata, Object snapshot)
   at Akka.Util.Internal.AtomicState.CallThrough(Func`1 task)
   at Akka.Util.Internal.AtomicState.CallThrough(Func`1 task)
```

This error is also visible in the failing checks on #357 

**Environment**
Currently occurring on both Windows 11 & Linux Docker with .NET 8.0

**Comment by mooreja-zia** [comment]
Resolved with Akka.Persistence.Redis 1.5.28 / 1.5.29
